=== dallefeste/it.bz.opendatahub.webcomponents/frontend/src/static/schemas/wcs-manifest-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://webcomponents.opendatahub.bz.it/schemas/v1/wcs-manifest",
    "title": "LineString",
	"type": "object",
    "definitions": {
        "entityOrPerson": {
            "type": "object",
            "items": {
				"name": "string",
				"email": "string",
				"organization": "string",
				"organizationUrl": {
					"type": "string",
					"format": "url"
				}
			},
			"required": ["name", "email"]
		},
		"stringArray": {
            "type": "array",
            "items": { "type": "string" },
			"uniqueItems": true,
			"minimum": 1,
            "default": []
		},
		"dist": {
			"type": "object",
			"items": {
				"basePath": "string",
				"files": { "$ref": "#/definitions/stringArray"}
			},
			"required": [
				"basePath",
				"files"
			]
		},
		"configuration": {
			"type": "object",
			"properties": {
				"tagName": {
					"type": "string"
				},
				"options": {
					"type": "array",
					"items": { "$ref": "#/definitions/configurationOption" },
					"uniqueItems": true,
					"minimum": 0,
					"default": []
				}
			},
			"required": [
				"tagName"
			]
		},
		"configurationOption": {
			"type": "object",
			"properties": {
				"key": {
					"type": "string"
				},
				"type": {
					"type": "string",
					"enum": [
						"select",
						"multiselect",
						"text",
						"null",
						"textarea",
						"bool",
						"object",
						"number"
					]
				},
				"label": {
					"type": "string"
				},
				"options": {
					"type": "object",
					"properties": {
						"values": {
							"$ref": "#/definitions/stringArray"
						},
						"default": {
						}
					}
				}
			},
			"required": [
				"key",
				"type",
				"options"
			]
		}
	},
    "properties": {
        "title": {
			"type": "string"
        },
        "description": {
			"type": "string"
		},
        "descriptionAbstract": {
			"type": "string"
		},
        "license": {
			"type": "string"
		},
        "copyrightHolders": {
            "type": "array",
            "minItems": 1,
            "items": { "$ref": "#/definitions/entityOrPerson" },
            "uniqueItems": true
		},
        "authors": {
			"type": "array",
            "minItems": 1,
            "items": { "$ref": "#/definitions/entityOrPerson" },
            "uniqueItems": true
		},
        "image": {
			"type": "string"
		},
        "searchTags": {
			"$ref": "#/definitions/stringArray"
		},
        "dist": {
			"$ref": "#/definitions/dist"
		},
        "configuration": {
			"$ref": "#/definitions/configuration"
		}
    },
    "required": [
		"title",
        "description",
        "descriptionAbstract",
        "license",
        "copyrightHolders",
        "authors",
        "image",
        "searchTags",
        "dist",
        "configuration"
    ]
}

=== dallefeste/it.bz.opendatahub.webcomponents/frontend/src/static/wcs-manifest-example.json
{
	"title": "Testable Web Component",
	"description": "This web component is used to test the validator",
	"descriptionAbstract": "A widget that helps to test all configurable options.",
	"license": "AGPL-3.0-or-later",
	"copyrightHolders": [
		{
			"name": "NOI",
			"email": "info@noi.bz.it",
			"organization": "NOI AG/SpA SÃ¼dtirol - Alto Adige",
			"organizationUrl": "https://noi.bz.it"
		}
	],
	"authors": [
		{
			"name": "Peter Moser",
			"email": "p.moser@noi.bz.it",
			"organization": "NOI S.p.A",
			"organizationUrl": "https://noi.bz.it"
		}
	],
	"image": "wcs-logo.png",
	"searchTags": ["testing", "tools"],
	"dist": {
		"basePath": "dist",
		"files": ["no-existing-widget.min.js"]
	},
	"configuration": {
		"tagName": "testable-widget",
		"options": [
			{
				"key": "option0",
				"type": "text",
				"label": "TEST option0: TEXT",
				"required": false,
				"options": {
					"default": "true"
				}
			},
			{
				"key": "option1",
				"type": "text",
				"label": "TEST option1: TEXT (required)",
				"required": true,
				"options": {
					"default": "default text 2"
				}
			},
			{
				"key": "option2",
				"type": "textarea",
				"label": "TEST option2: TEXTAREA",
				"required": false,
				"options": {
					"default": ""
				}
			},
			{
				"key": "option3",
				"type": "select",
				"label": "TEST option3: SELECT",
				"required": false,
				"options": {
					"values": ["en", "de", "it"],
					"default": "en"
				}
			},
			{
				"key": "option4",
				"type": "multiselect",
				"label": "TEST option4: MULTISELECT",
				"required": false,
				"options": {
					"values": ["en", "de", "it"],
					"default": "de"
				}
			},
			{
				"key": "option5",
				"type": "null",
				"label": "TEST option5: NULL FIELD (required)",
				"required": true,
				"options": {
					"default": true
				}
			}
		]
	}
}
